# Generated by Django 5.0.4 on 2024-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
