# Generated by Django 5.0.4 on 2024-04-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0002_patient_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='text',
            new_name='care_plan',
        ),
    ]
